### ISSUE TITLE
Dangr.Inject Tests are failing

### ISSUE THREAD

**Issue by Dangerdan9631** [Dangerdan9631/DangrLib#7]
## Expected Behavior
All unit tests should pass.

## Current Behavior
Dangr.Inject.Test InjectionCoreSetTest.TestSet is failing

```
Test method Dangr.Inject.InjectionCoreSetTest.TestSet threw exception: 
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.IEnumerable`1[Dangr.Inject.TestTypes+ISetClass]'.
    at Dangr.Inject.InjectionCore.Get[T](ProviderContext context) in D:\Source\git\DangrLib\src\Dangr.Inject\Inject\InjectionCore.cs:line 158
   at Dangr.Inject.InjectionCore.Get[T]() in D:\Source\git\DangrLib\src\Dangr.Inject\Inject\InjectionCore.cs:line 152
   at Dangr.Inject.InjectionCoreSetTest.TestSet() in D:\Source\git\DangrLib\src\Dangr.Inject.Test\InjectionCoreSetTest.cs:line 43
```

## Steps to Reproduce
1. Run unit tests in Dangr.Inject.Test

**Comment by Dangerdan9631** [comment]
Removing Dangr.Inject from 2.0 release since this is more of a framework than a utility library, and it needs some more design work.
